extract = 'total_dyn_inst: (\d+)'
benchmarks = 'benchmarks/*/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.tdce_only]
pipeline = [
    "bril2json",
    "target/release/localopts --dce",
    "bril2json",
    "brili -p {args}",
]

[runs.lvn_only]
pipeline = [
    "bril2json",
    "target/release/localopts --lvn",
    "bril2json",
    "brili -p {args}",
]

[runs.lvn_tdce]
pipeline = [
    "bril2json",
    "target/release/localopts --dce --lvn",
    "bril2json",
    "brili -p {args}",
]

